name: be_calm
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  carousel_slider: ^5.1.1
  provider: ^6.1.5+1
  lucide_icons: ^0.257.0
  video_player: ^2.10.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/video/
    - assets/splash/
    - assets/launcher/

flutter_native_splash:
  color: "#FF5FCF"
  image: assets/splash/Becalm.png
  
  android_12: 
    color: "#FF5FCF"
    image: assets/splash/Becalm.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/launcher.png"
  min_sdk_android: 21 
